// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhA-wy5NELL1MjFRY_keayxnNSjInALw',
    appId: '1:495840855051:web:ca2686feec423eec83f30e',
    messagingSenderId: '495840855051',
    projectId: 'banco1-1c444',
    authDomain: 'banco1-1c444.firebaseapp.com',
    storageBucket: 'banco1-1c444.firebasestorage.app',
    measurementId: 'G-NNWEJG991G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZ_t2DX0Us8dob0teafTSD8KfOgs-AQE',
    appId: '1:495840855051:android:e775164ac249469183f30e',
    messagingSenderId: '495840855051',
    projectId: 'banco1-1c444',
    storageBucket: 'banco1-1c444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQNA1NZIFNH2Y1H88A2n-O59cJ_w4qzFo',
    appId: '1:495840855051:ios:27c97af08c750aac83f30e',
    messagingSenderId: '495840855051',
    projectId: 'banco1-1c444',
    storageBucket: 'banco1-1c444.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQNA1NZIFNH2Y1H88A2n-O59cJ_w4qzFo',
    appId: '1:495840855051:ios:27c97af08c750aac83f30e',
    messagingSenderId: '495840855051',
    projectId: 'banco1-1c444',
    storageBucket: 'banco1-1c444.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
